### ISSUE TITLE
firebaseUserAuth vs User model

### ISSUE THREAD

**Issue by FilipeOS** [delay/flutter_firebase_auth_example#4]
Hi @delay ,

What's the difference between this two?
`final email = appState?.firebaseUserAuth?.email ?? '';`
`final nickName = appState?.user?.nickname ?? '';`

One you are getting from the firebaseUserAuth? and other from the User model? Thank you!

**Comment by delay** [comment]
firebaseUserAuth is from the firestore Auth method.  The second one would be from the user database collection.  I repeat some fields since the firebaseUserAuth only holds a few fields like the email address, encrypted password and uid of the user.  The user collection is just a regular database collection created by me and can hold anything I want.  `appState?.user?.email` could also grab the email address.  The other difference between the two is I am charged for reads to a regular collection but calls to firebase auth are free.  So probably why I pulled the email from there instead of the user collection.
